"""
Local Development URL Configuration

This script sets up local URLs for testing the Market Analyst application.
Run this to configure custom local domains instead of localhost.

Usage:
    python scripts/setup_local_urls.py

This will:
1. Add entries to /etc/hosts (requires sudo)
2. Generate SSL certificates for HTTPS testing
3. Update .env files with local URLs
"""

import os
import subprocess
import sys
from pathlib import Path

# Local domain configuration
LOCAL_DOMAINS = {
    "api": "api.market-analyst.local",
    "react": "app.market-analyst.local",
    "streamlit": "streamlit.market-analyst.local",
}

PORTS = {
    "api": 8000,
    "react": 5173,
    "streamlit": 8501,
}


def check_sudo():
    """Check if running with sudo privileges."""
    return os.geteuid() == 0 if hasattr(os, 'geteuid') else False


def setup_hosts_file():
    """Add local domains to /etc/hosts."""
    hosts_file = Path("/etc/hosts")
    
    if not hosts_file.exists():
        print("Error: /etc/hosts file not found")
        return False
    
    # Read current hosts
    with open(hosts_file, "r") as f:
        content = f.read()
    
    # Check if entries already exist
    entries_to_add = []
    for service, domain in LOCAL_DOMAINS.items():
        if domain not in content:
            entries_to_add.append(f"127.0.0.1 {domain}")
    
    if not entries_to_add:
        print("✓ Host entries already exist")
        return True
    
    # Add entries
    if not check_sudo():
        print("\nTo add host entries, run with sudo:")
        print(f"  sudo {sys.executable} {__file__}")
        print("\nOr manually add these to /etc/hosts:")
        for entry in entries_to_add:
            print(f"  {entry}")
        return False
    
    with open(hosts_file, "a") as f:
        f.write("\n# Market Analyst Local Development\n")
        for entry in entries_to_add:
            f.write(f"{entry}\n")
    
    print("✓ Added host entries to /etc/hosts")
    return True


def generate_env_file():
    """Generate .env file with local URLs."""
    env_content = f"""# Market Analyst - Local Development Configuration
# Generated by setup_local_urls.py

# LLM Configuration (Groq)
GROQ_API_KEY=your-groq-api-key-here
GROQ_MODEL=llama-3.3-70b-versatile
LLM_PROVIDER=groq

# Alternative: Gemini Configuration
# GEMINI_API_KEY=your-gemini-api-key-here
# GEMINI_MODEL=gemini-2.0-flash
# LLM_PROVIDER=gemini

# Backend API URL
API_BASE_URL=http://{LOCAL_DOMAINS['api']}:{PORTS['api']}

# Frontend URLs
REACT_APP_API_URL=http://{LOCAL_DOMAINS['api']}:{PORTS['api']}
STREAMLIT_SERVER_PORT={PORTS['streamlit']}

# Development Settings
LOG_LEVEL=DEBUG
LOG_FILE=dump.log

# Local Domains Reference:
# API:      http://{LOCAL_DOMAINS['api']}:{PORTS['api']}
# React:    http://{LOCAL_DOMAINS['react']}:{PORTS['react']}
# Streamlit: http://{LOCAL_DOMAINS['streamlit']}:{PORTS['streamlit']}
"""
    
    env_path = Path(".env.local")
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print(f"✓ Created {env_path}")
    print("\nCopy this to your main .env file:")
    print(f"  cp {env_path} .env")
    return True


def print_summary():
    """Print summary of local URLs."""
    print("\n" + "="*60)
    print("LOCAL DEVELOPMENT URLS")
    print("="*60)
    print(f"\nBackend API:     http://{LOCAL_DOMAINS['api']}:{PORTS['api']}")
    print(f"Health Check:    http://{LOCAL_DOMAINS['api']}:{PORTS['api']}/health")
    print(f"\nReact Frontend:  http://{LOCAL_DOMAINS['react']}:{PORTS['react']}")
    print(f"Streamlit:       http://{LOCAL_DOMAINS['streamlit']}:{PORTS['streamlit']}")
    print("\n" + "="*60)
    print("STARTUP COMMANDS")
    print("="*60)
    print(f"""
# 1. Terminal 1 - Start Backend
python3 -m uvicorn backend.api.fastapi_server:app \
  --host 0.0.0.0 --port {PORTS['api']} --reload

# 2. Terminal 2 - Start React Frontend  
cd react-directory
npm run dev -- --host 0.0.0.0 --port {PORTS['react']}

# 3. Terminal 3 - Start Streamlit (optional)
streamlit run frontend/streamlit_app.py \
  --server.port {PORTS['streamlit']} \
  --server.address 0.0.0.0
""")
    print("="*60)


def main():
    """Main setup function."""
    print("Market Analyst - Local URL Setup")
    print("=" * 40)
    
    # Setup hosts file
    setup_hosts_file()
    
    # Generate env file
    generate_env_file()
    
    # Print summary
    print_summary()


if __name__ == "__main__":
    main()
